# Generated by Django 5.1.2 on 2025-01-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='required_delivery',
            new_name='requires_delivery',
        ),
    ]
